name: CI

on: [push, pull_request]

defaults:
    run:
        shell: bash

jobs:
    unit_tests:
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]

        name: ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - name: Generate Project Files
              run: cmake . -B build -DBUILD_TESTS=ON

            - name: Build Dynamic Library and Unit Tests
              run: cmake --build build

            - name: Run Unit Tests
              working-directory: build
              run: ctest

            - name: Send Coverage to codecov.io
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: bash <(curl -s https://codecov.io/bash)

    memory_check:
        name: memory check
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Update Packages
              run: sudo apt update

            - name: Install Valgrind and SSH2
              run: sudo apt install -y valgrind libssh2-1

            - name: Generate Tests Build File
              run: cmake . -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug

            - name: Build Unit Tests
              run: cmake --build build

            - name: Run Unit Tests with Valgrind
              working-directory: build
              run: valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./unit_tests

    linter:
        name: linter
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install cpplint
              run: pip install cpplint

            - name: Run cpplint
              run: cpplint --linelength=140 --filter=-whitespace/indent,-whitespace/parens include/dylib.hpp